AWSTemplateFormatVersion: 2010-09-09
Description: 'Stack1 with yaml template'
Parameters:
    InstanceType:
        AllowedValues:
            - t1.micro
            - t2.nano
            - t2.micro
            - t2.small
            - t2.medium
            - t2.large
            - m1.small
            - m1.medium
            - m1.large
            - m1.xlarge
            - m2.xlarge
            - m2.2xlarge
            - m2.4xlarge
            - m3.medium
            - m3.large
            - m3.xlarge
            - m3.2xlarge
            - m4.large
            - m4.xlarge
            - m4.2xlarge
            - m4.4xlarge
            - m4.10xlarge
            - c1.medium
            - c1.xlarge
            - c3.large
            - c3.xlarge
            - c3.2xlarge
            - c3.4xlarge
            - c3.8xlarge
            - c4.large
            - c4.xlarge
            - c4.2xlarge
            - c4.4xlarge
            - c4.8xlarge
            - g2.2xlarge
            - g2.8xlarge
            - r3.large
            - r3.xlarge
            - r3.2xlarge
            - r3.4xlarge
            - r3.8xlarge
            - i2.xlarge
            - i2.2xlarge
            - i2.4xlarge
            - i2.8xlarge
            - d2.xlarge
            - d2.2xlarge
            - d2.4xlarge
            - d2.8xlarge
            - hi1.4xlarge
            - hs1.8xlarge
            - cr1.8xlarge
            - cc2.8xlarge
            - cg1.4xlarge
        ConstraintDescription: 'must be a valid EC2 instance type.'
        Default: t2.small
        Description: 'WebServer EC2 instance type'
        Type: String
    KeyName:
        ConstraintDescription: 'must be the name of an existing EC2 KeyPair.'
        Default: girish.pem
        Description: 'Name of an existing EC2 KeyPair to enable SSH access to the instance'
        Type: 'AWS::EC2::KeyPair::KeyName'
Resources:
    EC2Instance1:
        Properties:
            ImageId: ami-d3adb33f
            InstanceType:
                Ref: InstanceType
            KeyName: girish123.pem
        Type: 'AWS::EC2::Instance'
        Metadata:
            AWS::CloudFormation::Init: 
                configSets:
                    -"cowsay"
                cowsay:
                    packages:
                        yum:
                            cowsway: []
                    commands:
                        run_cosway:
                            command: "cowsway"
    SSHSecurityGroup:
        Properties:
            GroupDescription: 'Enable SSH access via port 22'
            SecurityGroupIngress:
                -
                    CidrIp: 0.0.0.0/0
                    FromPort: 22
                    IpProtocol: tcp
                    ToPort: 22
            VpcId: DefaultVPC
        Type: 'AWS::EC2::SecurityGroup'
